"""
Code generator for the Y language.

Transforms a validated AST into CASM148 assembly.
"""

from pathlib import Path
from ast_nodes import (
    Program, Function, CompoundStmt, VarDecl,
    ReturnStmt, ExpressionStmt, IfStmt, WhileStmt, DoWhileStmt, ForStmt,
    BreakStmt, ContinueStmt, GotoStmt, LabelStmt,
    IntLiteral, CharLiteral, StringLiteral, VarRef, BinaryOp, UnaryOp,
    PostfixOp, Assign, FuncCall, Type,
    ArrayAccess, Dereference, AddressOf,
    StructAccess, SizeOf
)
from utils import CompileError


class CodeGenerator:
    def __init__(self, filename='<input>', object_mode=False):
        self.filename = filename
        self.object_mode = object_mode
        self.asm = []
        self.label_counter = 0
        self.loop_stack = []  # tuples (cond_label, update_label, end_label)
        self.string_literals = {}  # value -> label

    def generate(self, program: Program):
        self.program = program
        self.asm.append("; Generated by ycc 0.1.0")
        self.asm.append("")
        self.asm.append(".text")

        if self.object_mode:
            self._emit_object_prelude(program)
        else:
            self.asm.append(".global _start")
            self.asm.append(".global main")
            self.asm.append(".org 0x00060000")
            self.asm.append("")
            self.asm.append("_start:")
            self.asm.append("    CLI")
            self.asm.append("    LDI.DW SP, 0x000FFF00")
            self.asm.append("    LDI.DW EX1, _heap_base")
            self.asm.append("    LDI.DW EX2, 12")
            self.asm.append("    ADD EX1, EX2")
            self.asm.append("    STR.DW EX1, [_heap_current]")
            self.asm.append("    STR.DW EX1, [_heap_start]")
            self.asm.append("    CALL main")
            self.asm.append("    HALT")
            self.asm.append("")

        for func in program.functions:
            if not func.is_declaration:
                self._generate_function(func)

        if not self.object_mode:
            self._emit("")
            self._emit("; Runtime library")
            self._emit_runtime()

        # All data must come after all code in flat binary mode.
        has_data = bool(program.globals) or bool(self.string_literals)
        if has_data:
            self._emit("")
            self._emit(".data")

        if program.globals:
            self._generate_globals(program.globals)

        if self.string_literals:
            for value, label in self.string_literals.items():
                escaped = self._escape_string(value)
                self._emit(f"{label}: .DB \"{escaped}\", 0")

        # Heap state for malloc/free.
        # _heap_base starts the state block; the actual heap begins 12 bytes later.
        # In flat mode _start initializes the heap pointers from _heap_base + 12.
        # In object mode crt0_y.asm performs the same initialization.
        self._emit("")
        self._emit("_heap_base:")
        self._emit("_heap_current: .DD 0")
        self._emit("_heap_start:   .DD 0")
        self._emit("_free_list:    .DD 0")
        self._emit("_heap_bottom:")

        return '\n'.join(self.asm) + '\n'

    def _emit_object_prelude(self, program: Program):
        """Emit .extern/.global directives for object mode."""
        externs = set()
        defined_functions = {f.name.upper() for f in program.functions if not f.is_declaration}
        has_main = 'MAIN' in defined_functions

        # Extern function declarations and variables.
        for func in program.functions:
            if func.is_declaration and func.linkage == 'external':
                externs.add(func.name.upper())
        for decl in program.globals:
            if decl.linkage == 'external' and decl.init is None:
                externs.add(decl.name.upper())

        # Collect called functions that are not defined in this module.
        for func in program.functions:
            if not func.is_declaration:
                self._collect_extern_calls(func.body, defined_functions, externs)

        # Heap symbols belong to the executable (the module that defines main).
        # Other object modules reference them through the linker.
        heap_symbols = ['_heap_base', '_heap_current', '_heap_start', '_free_list']
        if has_main:
            for sym in heap_symbols:
                externs.discard(sym.upper())
        else:
            for sym in heap_symbols:
                externs.add(sym.upper())

        for name in sorted(externs):
            self._emit(f".extern {name}")

        # Exported symbols: non-static functions and non-extern globals with storage.
        exports = []
        for func in program.functions:
            if not func.is_declaration and func.linkage != 'internal':
                exports.append(func.name)
        for decl in program.globals:
            if decl.linkage != 'internal' and not (decl.linkage == 'external' and decl.init is None):
                exports.append(decl.name)
        if has_main:
            for sym in heap_symbols:
                exports.append(sym)

        for name in sorted(set(exports)):
            self._emit(f".global {name}")

        if externs or exports:
            self._emit("")

    def _collect_extern_calls(self, stmt, defined_functions, externs):
        """Recursively collect function calls to undefined symbols."""
        from ast_nodes import FuncCall
        if stmt is None:
            return
        if isinstance(stmt, FuncCall):
            if stmt.name.upper() not in defined_functions:
                externs.add(stmt.name.upper())
            for arg in stmt.args:
                self._collect_extern_calls(arg, defined_functions, externs)
            return
        if isinstance(stmt, (IntLiteral, CharLiteral, StringLiteral, VarRef)):
            return
        # Recurse into common AST containers via attributes.
        for attr in ('stmts', 'body', 'then_stmt', 'else_stmt', 'stmt',
                     'init', 'cond', 'update', 'expr', 'left', 'right',
                     'operand', 'array', 'index'):
            val = getattr(stmt, attr, None)
            if val is None:
                continue
            if isinstance(val, list):
                for item in val:
                    self._collect_extern_calls(item, defined_functions, externs)
            else:
                self._collect_extern_calls(val, defined_functions, externs)

    def _emit(self, line):
        self.asm.append(line)

    @staticmethod
    def _escape_string(s):
        return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')

    def _string_literal_label(self, value):
        if value not in self.string_literals:
            self.string_literals[value] = self._new_label('str')
        return self.string_literals[value]

    def _init_local_string_array(self, sym, value):
        # Copy the string (including NUL) from a data label to the local array.
        label = self._string_literal_label(value)
        n = len(value) + 1
        loop_label = self._new_label('cp')
        done_label = self._new_label('cp_done')

        # dst address into EX1.
        self._generate_lvalue_address(VarRef(name=sym.name, symbol=sym))
        self._emit("    PUSH EX1")
        self._emit(f"    LDI.DW EX1, {label}")
        self._emit("    POP EX2")
        # EX1 = src, EX2 = dst
        self._emit(f"    LDI.DW EX3, {n}")
        self._emit(f"{loop_label}:")
        self._emit("    CMP.DW EX3, 0")
        self._emit(f"    JMP.EQ {done_label}")
        self._emit("    LOD.B XL4, [EX1]")
        self._emit("    STR.B XL4, [EX2]")
        self._emit("    INC EX1")
        self._emit("    INC EX2")
        self._emit("    DEC EX3")
        self._emit(f"    JMP {loop_label}")
        self._emit(f"{done_label}:")

    def _emit_runtime(self):
        runtime_path = Path(__file__).resolve().parent / 'stdlib' / 'runtime.asm'
        if runtime_path.exists():
            text = runtime_path.read_text(encoding='utf-8')
            for line in text.splitlines():
                self._emit(line)
        else:
            self._emit("; WARNING: runtime.asm not found")

    def _new_label(self, prefix='L'):
        self.label_counter += 1
        return f"_y_{prefix}_{self.label_counter}"

    def _generate_globals(self, globals):
        # All globals are emitted in the single .data section at the end.
        for decl in globals:
            # Pure extern declarations do not allocate storage.
            if decl.linkage == 'external' and decl.init is None:
                continue

            if decl.type.is_array():
                self._generate_global_array(decl)
                continue

            size = decl.type.size()
            if decl.init is not None:
                if isinstance(decl.init, StringLiteral):
                    label = self._string_literal_label(decl.init.value)
                    self._emit(f"{decl.name}: .DD {label}")
                else:
                    value = decl.init.value
                    if size == 1:
                        self._emit(f"{decl.name}: .DB {value}")
                    elif size == 2:
                        self._emit(f"{decl.name}: .DW {value}")
                    else:
                        self._emit(f"{decl.name}: .DD {value}")
            else:
                if decl.type.is_struct():
                    self._emit(f"{decl.name}:")
                    self._emit_zero_bytes(size)
                elif size == 1:
                    self._emit(f"{decl.name}: .DB 0")
                elif size == 2:
                    self._emit(f"{decl.name}: .DW 0")
                else:
                    self._emit(f"{decl.name}: .DD 0")

    def _generate_global_array(self, decl: VarDecl):
        elem_type = decl.type.element_type()
        elem_size = elem_type.size()
        total_bytes = decl.type.size()
        if decl.init is not None and isinstance(decl.init, StringLiteral):
            escaped = self._escape_string(decl.init.value)
            self._emit(f'{decl.name}: .DB "{escaped}", 0')
            # Pad if the explicit array size is larger than the string.
            pad = total_bytes - (len(decl.init.value) + 1)
            if pad > 0:
                self._emit_zero_bytes(pad)
            return
        # Zero-initialized array.
        if elem_size == 1:
            self._emit_zero_bytes(total_bytes)
        elif elem_size == 2:
            for _ in range(total_bytes // 2):
                self._emit(f"    .DW 0")
        else:
            for _ in range(total_bytes // 4):
                self._emit(f"    .DD 0")

    def _emit_zero_bytes(self, n):
        # Emit zeros in chunks to keep lines short.
        chunk = 16
        while n > 0:
            c = min(n, chunk)
            self._emit(f"    .DB {', '.join(['0'] * c)}")
            n -= c

    def _generate_function(self, func: Function):
        ret_label = f"_y_ret_{func.name}"

        self._emit(f"{func.name}:")
        self._emit("    PUSH BP")
        self._emit("    COPY BP, SP")
        if func.locals_size > 0:
            self._emit(f"    ADD.DW SP, {func.locals_size}")

        has_explicit_return = False
        for stmt in func.body.stmts:
            self._generate_statement(stmt, ret_label)
            if isinstance(stmt, ReturnStmt):
                has_explicit_return = True

        if func.type.base != 'void' and not has_explicit_return:
            self._emit("    LDI.DW EX1, 0")
            self._emit(f"    JMP {ret_label}")

        self._emit(f"{ret_label}:")
        self._emit("    COPY SP, BP")
        self._emit("    POP BP")
        self._emit("    RET")
        self._emit("")

    def _generate_statement(self, stmt, ret_label):
        if isinstance(stmt, VarDecl):
            if stmt.init is not None:
                if stmt.type.is_array() and stmt.type.base == 'char' and isinstance(stmt.init, StringLiteral):
                    self._init_local_string_array(stmt.symbol, stmt.init.value)
                else:
                    self._generate_expression(stmt.init)
                    self._store_to_symbol(stmt.symbol)
        elif isinstance(stmt, ExpressionStmt):
            if stmt.expr is not None:
                self._generate_expression(stmt.expr)
        elif isinstance(stmt, ReturnStmt):
            if stmt.expr is not None:
                self._generate_expression(stmt.expr)
            self._emit(f"    JMP {ret_label}")
        elif isinstance(stmt, IfStmt):
            self._generate_if(stmt, ret_label)
        elif isinstance(stmt, WhileStmt):
            self._generate_while(stmt, ret_label)
        elif isinstance(stmt, DoWhileStmt):
            self._generate_do_while(stmt, ret_label)
        elif isinstance(stmt, ForStmt):
            self._generate_for(stmt, ret_label)
        elif isinstance(stmt, BreakStmt):
            if not self.loop_stack:
                raise CompileError("break outside of loop")
            self._emit(f"    JMP {self.loop_stack[-1][2]}")
        elif isinstance(stmt, ContinueStmt):
            if not self.loop_stack:
                raise CompileError("continue outside of loop")
            # update label for for-loop, cond label for while/do-while.
            self._emit(f"    JMP {self.loop_stack[-1][1]}")
        elif isinstance(stmt, GotoStmt):
            self._emit(f"    JMP {stmt.label}")
        elif isinstance(stmt, LabelStmt):
            self._emit(f"{stmt.label}:")
            self._generate_statement(stmt.stmt, ret_label)
        elif isinstance(stmt, CompoundStmt):
            for s in stmt.stmts:
                self._generate_statement(s, ret_label)
        else:
            raise CompileError(f"unsupported statement: {type(stmt).__name__}")

    def _generate_if(self, stmt: IfStmt, ret_label):
        else_label = self._new_label('else') if stmt.else_stmt else None
        end_label = self._new_label('endif')

        self._generate_expression(stmt.cond)
        self._emit_test_zero_and_jump(else_label if else_label else end_label)

        self._generate_statement(stmt.then_stmt, ret_label)
        if stmt.else_stmt:
            self._emit(f"    JMP {end_label}")
            self._emit(f"{else_label}:")
            self._generate_statement(stmt.else_stmt, ret_label)
        self._emit(f"{end_label}:")

    def _generate_while(self, stmt: WhileStmt, ret_label):
        start_label = self._new_label('while_start')
        cond_label = start_label
        update_label = start_label
        end_label = self._new_label('while_end')
        self.loop_stack.append((cond_label, update_label, end_label))

        self._emit(f"{start_label}:")
        self._generate_expression(stmt.cond)
        self._emit_test_zero_and_jump(end_label)
        self._generate_statement(stmt.body, ret_label)
        self._emit(f"    JMP {start_label}")
        self._emit(f"{end_label}:")

        self.loop_stack.pop()

    def _generate_do_while(self, stmt: DoWhileStmt, ret_label):
        start_label = self._new_label('do_start')
        cond_label = self._new_label('do_cond')
        end_label = self._new_label('do_end')
        self.loop_stack.append((cond_label, cond_label, end_label))

        self._emit(f"{start_label}:")
        self._generate_statement(stmt.body, ret_label)
        self._emit(f"{cond_label}:")
        self._generate_expression(stmt.cond)
        self._emit_test_nonzero_and_jump(start_label)
        self._emit(f"{end_label}:")

        self.loop_stack.pop()

    def _generate_for(self, stmt: ForStmt, ret_label):
        cond_label = self._new_label('for_cond')
        update_label = self._new_label('for_update')
        end_label = self._new_label('for_end')
        self.loop_stack.append((cond_label, update_label, end_label))

        if stmt.init is not None:
            if isinstance(stmt.init, list):
                for d in stmt.init:
                    self._generate_statement(d, ret_label)
            else:
                self._generate_expression(stmt.init)
        self._emit(f"    JMP {cond_label}")
        self._emit(f"{update_label}:")
        if stmt.update is not None:
            self._generate_expression(stmt.update)
        self._emit(f"{cond_label}:")
        if stmt.cond is not None:
            self._generate_expression(stmt.cond)
            self._emit_test_zero_and_jump(end_label)
        self._generate_statement(stmt.body, ret_label)
        self._emit(f"    JMP {update_label}")
        self._emit(f"{end_label}:")

        self.loop_stack.pop()

    def _emit_test_zero_and_jump(self, target):
        self._emit("    LDI.DW EX2, 0")
        self._emit("    CMP EX1, EX2")
        self._emit(f"    JMP.EQ {target}")

    def _emit_test_nonzero_and_jump(self, target):
        self._emit("    LDI.DW EX2, 0")
        self._emit("    CMP EX1, EX2")
        self._emit(f"    JMP.NE {target}")

    def _emit_boolify_ex1(self):
        true_label = self._new_label('bool_true')
        self._emit("    LDI.DW EX2, 0")
        self._emit("    CMP EX1, EX2")
        self._emit("    LDI.DW EX1, 1")
        self._emit(f"    JMP.NE {true_label}")
        self._emit("    LDI.DW EX1, 0")
        self._emit(f"{true_label}:")

    def _generate_expression(self, expr):
        if isinstance(expr, IntLiteral):
            self._emit(f"    LDI.DW EX1, {expr.value}")
            return

        if isinstance(expr, CharLiteral):
            self._emit(f"    LDI.DW EX1, {expr.value}")
            return

        if isinstance(expr, StringLiteral):
            if expr.value not in self.string_literals:
                label = self._new_label('str')
                self.string_literals[expr.value] = label
            self._emit(f"    LDI.DW EX1, {self.string_literals[expr.value]}")
            return

        if isinstance(expr, VarRef):
            if expr.symbol.type.is_array():
                # Array-to-pointer decay.
                self._emit_lvalue_address_symbol(expr.symbol)
            else:
                self._load_symbol(expr.symbol)
            return

        if isinstance(expr, Dereference):
            self._load_lvalue_value(expr)
            return

        if isinstance(expr, AddressOf):
            self._generate_lvalue_address(expr.operand)
            return

        if isinstance(expr, ArrayAccess):
            self._load_lvalue_value(expr)
            return

        if isinstance(expr, StructAccess):
            self._load_lvalue_value(expr)
            return

        if isinstance(expr, Assign):
            self._generate_expression(expr.right)
            if expr.op == '=':
                self._store_to_lvalue(expr.left)
            else:
                # Compound assignment: left op= right.
                self._emit("    PUSH EX1")
                self._load_lvalue_value(expr.left)
                self._emit("    POP EX2")
                op_map = {
                    '+=': 'ADD', '-=': 'SUB', '*=': 'MUL', '/=': 'DIV', '%=': 'REM',
                    '&=': 'AND', '|=': 'OR', '^=': 'XOR',
                }
                if expr.op not in op_map:
                    raise CompileError(f"unsupported assignment operator: {expr.op}")
                # Pointer +=/-= scales by pointee size.
                if expr.left.type.pointer > 0 and expr.op in ('+=', '-='):
                    self._scale_value_by_size("EX2", expr.left.type.pointee_type().size())
                self._emit(f"    {op_map[expr.op]} EX1, EX2")
                self._store_to_lvalue(expr.left)
            return

        if isinstance(expr, UnaryOp):
            self._generate_expression(expr.operand)
            if expr.op == '+':
                return
            elif expr.op == '-':
                self._emit("    LDI.DW EX2, 0")
                self._emit("    SUB EX2, EX1")
                self._emit("    COPY EX1, EX2")
            elif expr.op == '~':
                self._emit("    NOT EX1")
            elif expr.op == '!':
                self._emit_boolify_ex1()
                # Invert boolean result.
                self._emit("    LDI.DW EX2, 1")
                self._emit("    XOR EX1, EX2")
            elif expr.op in ('++', '--'):
                operand_type = expr.operand.type
                if operand_type.pointer > 0:
                    delta = operand_type.pointee_type().size()
                else:
                    delta = 1
                self._emit(f"    LDI.DW EX2, {delta}")
                if expr.op == '++':
                    self._emit("    ADD EX1, EX2")
                else:
                    self._emit("    SUB EX1, EX2")
                self._store_to_lvalue(expr.operand)
            else:
                raise CompileError(f"unsupported unary operator: {expr.op}")
            return

        if isinstance(expr, PostfixOp):
            if expr.op in ('++', '--'):
                operand_type = expr.operand.type
                delta = operand_type.pointee_type().size() if operand_type.pointer > 0 else 1
                # Load old value, modify lvalue, leave old value on the stack.
                self._load_lvalue_value(expr.operand)
                self._emit("    PUSH EX1")
                self._emit("    COPY EX2, EX1")
                self._emit(f"    LDI.DW EX3, {delta}")
                if expr.op == '++':
                    self._emit("    ADD EX2, EX3")
                else:
                    self._emit("    SUB EX2, EX3")
                self._emit("    COPY EX1, EX2")
                self._store_to_lvalue(expr.operand)
                self._emit("    POP EX1")
            else:
                raise CompileError(f"unsupported postfix operator: {expr.op}")
            return

        if isinstance(expr, BinaryOp):
            if expr.op == '&&':
                self._generate_short_circuit_and(expr)
                return
            if expr.op == '||':
                self._generate_short_circuit_or(expr)
                return

            lt = expr.left.type
            rt = expr.right.type
            if expr.op == '+' and lt.pointer > 0 and rt.pointer == 0:
                self._emit_pointer_arith(expr.left, expr.right,
                                         lt.pointee_type().size(), subtract=False)
                return
            if expr.op == '+' and rt.pointer > 0 and lt.pointer == 0:
                self._emit_pointer_arith(expr.right, expr.left,
                                         rt.pointee_type().size(), subtract=False)
                return
            if expr.op == '-' and lt.pointer > 0 and rt.pointer == 0:
                self._emit_pointer_arith(expr.left, expr.right,
                                         lt.pointee_type().size(), subtract=True)
                return

            self._generate_expression(expr.right)
            self._emit("    PUSH EX1")
            self._generate_expression(expr.left)
            self._emit("    POP EX2")

            if expr.op in ('+', '-', '*', '/', '%', '&', '|', '^'):
                op_map = {
                    '+': 'ADD', '-': 'SUB', '*': 'MUL', '&': 'AND', '|': 'OR', '^': 'XOR',
                }
                if expr.op in ('/', '%'):
                    # Signed division when both operands are signed; otherwise unsigned.
                    if lt.unsigned or rt.unsigned:
                        op_map['/'] = 'DIV'
                        op_map['%'] = 'REM'
                    else:
                        op_map['/'] = 'IDIV'
                        op_map['%'] = 'IREM'
                self._emit(f"    {op_map[expr.op]} EX1, EX2")
            elif expr.op in ('<<', '>>'):
                if not isinstance(expr.right, IntLiteral):
                    raise CompileError("variable shift count not supported in MVP")
                shift = expr.right.value
                if expr.op == '<<':
                    self._emit(f"    LSL EX1, {shift}")
                else:
                    self._emit(f"    ASR EX1, {shift}")
            elif expr.op in ('==', '!=', '<', '>', '<=', '>='):
                if expr.op in ('<', '>', '<=', '>='):
                    self._emit("    ICMP EX1, EX2")
                else:
                    self._emit("    CMP EX1, EX2")
                cond_map = {
                    '==': 'EQ', '!=': 'NE',
                    '<': 'LS', '>': 'GR', '<=': 'LE', '>=': 'GE',
                }
                true_label = self._new_label('cmp_true')
                self._emit("    LDI.DW EX1, 1")
                self._emit(f"    JMP.{cond_map[expr.op]} {true_label}")
                self._emit("    LDI.DW EX1, 0")
                self._emit(f"{true_label}:")
            else:
                raise CompileError(f"unsupported binary operator: {expr.op}")
            return

        if isinstance(expr, FuncCall):
            for arg in reversed(expr.args):
                self._generate_expression(arg)
                self._emit("    PUSH EX1")
            self._emit(f"    CALL {expr.name}")
            if expr.args:
                # i80148 stack grows upward: remove arguments by decreasing SP.
                self._emit(f"    SUB.DW SP, {4 * len(expr.args)}")
            return

        if isinstance(expr, SizeOf):
            self._emit(f"    LDI.DW EX1, {expr.size}")
            return

        raise CompileError(f"unsupported expression: {type(expr).__name__}")

    def _generate_short_circuit_and(self, expr: BinaryOp):
        false_label = self._new_label('and_false')
        done_label = self._new_label('and_done')
        self._generate_expression(expr.left)
        self._emit_test_zero_and_jump(false_label)
        self._generate_expression(expr.right)
        self._emit_boolify_ex1()
        self._emit(f"    JMP {done_label}")
        self._emit(f"{false_label}:")
        self._emit("    LDI.DW EX1, 0")
        self._emit(f"{done_label}:")

    def _generate_short_circuit_or(self, expr: BinaryOp):
        true_label = self._new_label('or_true')
        done_label = self._new_label('or_done')
        self._generate_expression(expr.left)
        self._emit_test_nonzero_and_jump(true_label)
        self._generate_expression(expr.right)
        self._emit_boolify_ex1()
        self._emit(f"    JMP {done_label}")
        self._emit(f"{true_label}:")
        self._emit("    LDI.DW EX1, 1")
        self._emit(f"{done_label}:")

    def _store_to_lvalue(self, expr):
        if isinstance(expr, VarRef):
            self._store_to_symbol(expr.symbol)
        elif isinstance(expr, Dereference):
            # EX1 holds value to store; address is in the dereferenced operand.
            self._emit("    COPY EX2, EX1")
            self._generate_expression(expr.operand)
            suffix = expr.type.suffix()
            self._emit(f"    STR.{suffix} EX2, [EX1]")
        elif isinstance(expr, ArrayAccess):
            self._emit("    PUSH EX1")
            self._generate_lvalue_address(expr)
            self._emit("    POP EX2")
            suffix = expr.type.suffix()
            self._emit(f"    STR.{suffix} EX2, [EX1]")
        elif isinstance(expr, StructAccess):
            self._emit("    PUSH EX1")
            self._generate_lvalue_address(expr)
            self._emit("    POP EX2")
            suffix = expr.field_type.suffix()
            self._emit(f"    STR.{suffix} EX2, [EX1]")
        else:
            raise CompileError("left side of assignment must be an lvalue")

    def _emit_sign_extend(self, size):
        """Sign-extend EX1 from byte/word to dword."""
        if size == 1:
            self._emit("    LSL EX1, 24")
            self._emit("    ASR EX1, 24")
        elif size == 2:
            self._emit("    LSL EX1, 16")
            self._emit("    ASR EX1, 16")

    def _load_symbol(self, sym):
        if sym.kind == 'global':
            if self.object_mode:
                # CASM148 object mode has a relocation bug for LOD/STR with
                # absolute memory addresses. Use register-indirect addressing.
                self._emit(f"    LDI.DW EX2, {sym.label}")
                self._emit(f"    LOD.{sym.type.suffix()} EX1, [EX2]")
            else:
                self._emit(f"    LOD.{sym.type.suffix()} EX1, [{sym.label}]")
        elif sym.kind == 'local':
            self._emit(f"    LOD.{sym.type.suffix()} EX1, [BP+{sym.offset}]")
        else:  # param
            self._emit(f"    LOD.{sym.type.suffix()} EX1, [BP-{sym.offset}]")
        # Sign-extend signed char/short values after load.
        if sym.type.size() < 4 and not sym.type.unsigned:
            self._emit_sign_extend(sym.type.size())

    def _store_to_symbol(self, sym):
        if sym.kind == 'global':
            if self.object_mode:
                # See _load_symbol: avoid absolute-address LOD/STR in object mode.
                self._emit("    PUSH EX1")
                self._emit(f"    LDI.DW EX1, {sym.label}")
                self._emit("    COPY EX2, EX1")
                self._emit("    POP EX1")
                self._emit(f"    STR.{sym.type.suffix()} EX1, [EX2]")
            else:
                self._emit(f"    STR.{sym.type.suffix()} EX1, [{sym.label}]")
        elif sym.kind == 'local':
            self._emit(f"    STR.{sym.type.suffix()} EX1, [BP+{sym.offset}]")
        else:  # param
            self._emit(f"    STR.{sym.type.suffix()} EX1, [BP-{sym.offset}]")

    def _emit_lvalue_address_symbol(self, sym):
        if sym.kind == 'global':
            self._emit(f"    LDI.DW EX1, {sym.label}")
        elif sym.kind == 'local':
            self._emit("    COPY EX1, BP")
            if sym.offset != 0:
                self._emit(f"    LDI.DW EX2, {sym.offset}")
                self._emit("    ADD EX1, EX2")
        else:  # param
            self._emit("    COPY EX1, BP")
            if sym.offset != 0:
                self._emit(f"    LDI.DW EX2, {sym.offset}")
                self._emit("    SUB EX1, EX2")

    def _generate_lvalue_address(self, expr):
        if isinstance(expr, VarRef):
            self._emit_lvalue_address_symbol(expr.symbol)
        elif isinstance(expr, Dereference):
            self._generate_expression(expr.operand)
        elif isinstance(expr, ArrayAccess):
            self._generate_expression(expr.index)
            self._emit("    PUSH EX1")
            self._generate_expression(expr.array)
            self._emit("    POP EX2")
            # EX1 = base pointer, EX2 = index
            self._scale_value_by_size("EX2", expr.type.size())
            self._emit("    ADD EX1, EX2")
        elif isinstance(expr, StructAccess):
            if expr.arrow:
                self._generate_expression(expr.operand)
            else:
                self._generate_lvalue_address(expr.operand)
            if expr.field_offset != 0:
                self._emit(f"    LDI.DW EX2, {expr.field_offset}")
                self._emit("    ADD EX1, EX2")
        else:
            raise CompileError("not an lvalue")

    def _load_lvalue_value(self, expr):
        if isinstance(expr, VarRef):
            self._load_symbol(expr.symbol)
        else:
            self._generate_lvalue_address(expr)
            suffix = expr.type.suffix()
            self._emit(f"    LOD.{suffix} EX1, [EX1]")
            # Sign-extend signed char/short values after load.
            if expr.type.size() < 4 and not expr.type.unsigned:
                self._emit_sign_extend(expr.type.size())

    def _scale_value_by_size(self, reg, size):
        """Multiply value in `reg` by `size` using shift or MUL."""
        if size == 1:
            return
        if size == 2:
            self._emit(f"    LSL {reg}, 1")
        elif size == 4:
            self._emit(f"    LSL {reg}, 2")
        else:
            self._emit(f"    LDI.DW EX7, {size}")
            self._emit(f"    MUL {reg}, EX7")

    def _emit_pointer_arith(self, base_expr, offset_expr, elem_size, subtract):
        self._generate_expression(offset_expr)
        self._emit("    PUSH EX1")
        self._generate_expression(base_expr)
        self._emit("    POP EX2")
        self._scale_value_by_size("EX2", elem_size)
        if subtract:
            self._emit("    SUB EX1, EX2")
        else:
            self._emit("    ADD EX1, EX2")
